services:
  db:
    image: "postgres:alpine"
    restart: "always"
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD

  backend:
    build: ./backend
    ports:
      - 3001:3000
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend