version: "3.9"

services:
  db:
    image: "postgres:alpine"
    container_name: db
    restart: "always"
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    networks:
      - internal

  db-test:
    profiles: ["test"]
    image: "postgres:alpine"
    restart: "always"
    ports:
      - 5555:5432
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    networks:
      - internal

  backend:
    build: ./backend
    container_name: backend
    ports:
      - 3001:3001
      - 9229:9229
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    networks:
      - internal
    command: pnpm run start:debug

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend
    networks:
      - internal

  storybook:
    image: storybook
    build: ./frontend
    container_name: storybook
    init: true
    command: pnpm run storybook --disable-telemetry
    ports:
      - 6006:6006
    volumes:
      - ./frontend:/frontend

networks:
  internal:
    driver: bridge
