name: Main branch CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  backend:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install
        working-directory: ./backend
        run: npm i
      - name: lint
        working-directory: ./backend
        run: npm lint
      - name: test
        working-directory: ./backend
        run: npm test
  frontend:
    needs: ["backend"]
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install
        working-directory: ./frontend
        run: npm i
      - name: lint
        working-directory: ./frontend
        run: npm lint
      - name: test
        working-directory: ./frontend
        run: npm test
